import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { getComics } from '../lib/getComics';
import { ComicsProvider } from '../context/ComicsContext';

// Next.js 14で利用可能なフォントに変更
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const comics = await getComics();

  return (
    <html lang="ja">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <Header />
        <ComicsProvider initialComics={comics}>
          {children}
        </ComicsProvider>
        <Footer />
      </body>
    </html>
  );
}
