import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/Footer";
import { getComics } from '../lib/getComics';
import { ComicsProvider } from '../context/ComicsContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const comics = await getComics();

  return (
    <html lang="ja">
      <body>
        <ComicsProvider initialComics={comics}>
          {children}
        </ComicsProvider>
        <Footer />
      </body>
    </html>
  );
}
